### ISSUE TITLE
Failed to build on Rust 1.40.0

### ISSUE THREAD

**Issue by tesuji** [thepowersgang/utf16_literal-rs#1]

**Comment by thepowersgang** [comment]
A description saying how it fails would have been appreciated. I assume the error you're getting is related to the `#![feature]` annotations?

**Comment by tesuji** [comment]
Sorry. I misread and used the 0.1 version of this crate.
Sorry for any uncomfortable I did.

**Comment by tesuji** [comment]
Oh. You pushed the new version today. Anyway, thanks for the work.
